{% set name = "pdfminer.six" %}
{% set version = "20170419" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "8dc0c05c8fa84e7d06933896be815a3e69f65dad4a19070dfa56e70afa5e1588" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  
  run:
    - python
    - six
    - pycrypto
    - chardet  # [py3k]

test:
  imports:
    - pdfminer

  commands:
    - pdf2txt.py -h
    # Can't test dumppdf.py b/c -h apparently raises issues.
    # Can't test latin2ascii.py unless you feed it input.
    # Can't test dumppdf.py unless you feed it input.

about:
  home: https://github.com/pdfminer/pdfminer.six
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'PDF parser and analyzer'
  dev_url: https://github.com/pdfminer/pdfminer.six

extra:
  recipe-maintainers:
    - pmlandwehr
