{% set name = "pdfminer.six" %}
{% set version = "20250327" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfminer_six-{{ version }}.tar.gz
  sha256: 57f6c34c2702df04cfa3191622a3db0a922ced686d35283232b00094f8914aa1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
    - packaging >=24.2
  run:
    - python >=3.9
    - charset-normalizer >=2.0.0
    - cryptography >=36.0.0
    - packaging >=24.2

test:
  imports:
    - pdfminer
  commands:
    - pip check
  requires:
    - pip

about:
  summary: PDF parser and analyzer
  license: MIT
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/78379
    reason: Dependency for pdfplumber
  recipe-maintainers:
    - ianaobi
