{% set name = "pdfminer.six" %}
{% set version = "20181108" %}
{% set author = "pdfminer %}
{% set sha256 = "99b2bf8e2154e617c88bba7ea4f3fd02fb7d5b7be6b441a9001ca29d54d255f4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/{{ version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - six
    - pycryptodome
    - sortedcontainers
    - chardet

test:
  imports:
    - pdfminer

  commands:
    - pdf2txt.py -h
    # Can't test dumppdf.py b/c -h raises issues.
    # Can't test latin2ascii.py unless you feed it input.

about:
  home: https://github.com/pdfminer/pdfminer.six
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'PDF parser and analyzer'
  dev_url: https://github.com/pdfminer/pdfminer.six

extra:
  recipe-maintainers:
    - pmlandwehr
    - pvanheus
