{% set name = "pdfminer.six" %}
{% set author = "pdfminer" %}
{% set version = "20181108" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "99b2bf8e2154e617c88bba7ea4f3fd02fb7d5b7be6b441a9001ca29d54d255f4" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://github.com/{{ author }}/{{ name }}/archive/{{ version}}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  
  run:
    - python
    - six
    - pycrypto
    - sortedcontainers
    - chardet  # [py3k]

test:
  imports:
    - pdfminer

  commands:
    - pdf2txt.py -h
    # Can't test dumppdf.py b/c -h raises issues.
    # Can't test latin2ascii.py unless you feed it input.

about:
  home: https://github.com/pdfminer/pdfminer.six
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'PDF parser and analyzer'
  dev_url: https://github.com/pdfminer/pdfminer.six

extra:
  recipe-maintainers:
    - pmlandwehr
