travis:
  secure:
    BINSTAR_TOKEN: hgNNv19cidV6a2XAXid+RQmdLJnP+sVMQ4gCadrTYPps53Q9AUcdBefZ8VmAm0InLVBi9leVy+PfrB2YG4xJfERo+6aiffHyXS4cYcKky0lEcGQfxfsQJ627YeYp36OfFnBXH9ZOevniGmrE92qiGWA4C6aB5Z3dWSAdCr5AUkft7NY//9BBiaBUvf3W5QlTgqG1UjE1xqJgsRGTK6jGEdY8c8iuL8P5HhvQVkElVz4R9xz6mY1RMM8YkapII82spcjzkdVJbw9KhlPxnxqM4mm+/9ogUMbygS2ic7gK+GzGJpFXqME+IK/9h8QwSRQ8QVe+21gu7ObTDYHez//eokhAXF+SCYAiDXXKcKKLnpPDHmaUuDVkGXPz6nqdrdHg1zh7Q2SBsLuy8kWtHvLxu+jqxoz7z5MvU5mVmD3fVQ464BSFOxFdUGMOWx1XEV6oz8dLjRqOzGGUv/VLmvwZcjewLhbMQn/k1mBp519NJTQZBXhcSPiVIlCCMsEuVW63n86bulF7drFL4WuEE/T8TaNkuOGhDMsmS78pI/FhgzaJfIGFzuNMLFdjwvInQ+p0W46iYU2t2tKfLLkXD9AHKCuiCBEqV6qfcJ3Yx04+Bqqlw8wOofRPM2sN2LwlqCIHFC6zNcVJSk2e+wAXWgMDuXd9KOKFgrhLg31jmSjKO5o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
