travis:
  secure:
    BINSTAR_TOKEN: ORw0jkBjBYTi9wAkVA93j8mEE00y2laGXzT86gWKWe/rcd3g3dqrZi1o2D4Ih23pl/cRvqxKbMGcjjHhYjqiBrzXNyiZwmYJ40GdMZyp5Vl/lvRGKEeqSKlf9MerxbSGXx8phaO+pAHF83ul+n/gT9dzImfR3mVNRlicYO6W6NQQHREiEPoid4AFvsVlATMsa8bBkRqOsVM0/84napVaW1deVazLHUdNYI2Zytj3cncmElTKiawB/61k+HSkuYldeJrICKwvjFd7JZvI+7JF36e5Gkxz+F6tfW1Lu4YkR5X6EYFa2xr6OSJ69zub1XcnIJUne4Qwkg1OnfUFKIXRhDt2hdt6c5AJQMZvZjT9HoAQKzq5nwIKog6I6zmmfv77hdkfQF5fujKztHZyPsd/UBSGAwuLF0/BHRSbehrndjsdpXW8aDYamO/3OxUX8svSLPYw0L9/OCKEU462n+vzqxFUsa16CdqWsJNdwlhafGNo4nPMAJ+5nxrs6Pk5/1Vh28zEXV6Ny9sYC8aqO/jy7+3YIWWf9KNWaYTvMJt9ZY1vE5fdMeepdJxwKOPpZ5cNMLvWAnO6NaLgPbeDF+fuUXKS5vpkq8jEYb+Vhw4SkjVbnImS6uqkBGcASFKlNo8GAgXiPUb95pVAswc63eX++5rOD7q8k9nN+LBP5Ukx+Z0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
